kind: pipeline
name: amd64
platform:
  os: linux
  arch: amd64
steps:
- name: docker
  image: plugins/docker
  settings:
    repo: quay.io/revoman/edgetpu-device-plugin
    tags: amd64
    registry: quay.io
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
- name: docker-sample
  image: plugins/docker
  settings:
    repo: quay.io/kkohtaka/edgetpu-demo
    tags: amd64
    dockerfile: samples/Dockerfile
    context: samples/
    registry: quay.io
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
trigger:
  branch:
  - master
  event:
  - push
---
kind: pipeline
name: arm32
platform:
  os: linux
  arch: arm
steps:
- name: docker
  image: plugins/docker
  settings:
    repo: quay.io/revoman/edgetpu-device-plugin
    tags: arm32
    build_args:
    - DEBIAN_BASE_SUFFIX=arm
    - GO_TARBALL=go1.11.linux-armv6l.tar.gz
    - SO_SUFFIX=arm32
    - LIB_PATH=/lib/arm-linux-gnueabihf
    registry: quay.io
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
- name: docker-sample
  image: plugins/docker
  settings:
    repo: quay.io/kkohtaka/edgetpu-demo
    tags: arm32
    dockerfile: samples/Dockerfile
    context: samples/
    build_args:
    - DEBIAN_BASE_SUFFIX=arm
    registry: quay.io
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
trigger:
  branch:
  - master
  event:
  - push
