[[constraint]]
  name = "github.com/fsnotify/fsnotify"
  version = "1.4.7"

[[constraint]]
  name = "k8s.io/klog"
  version = "0.2.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "v0.18.19"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "v1.18.19"

[prune]
  go-tests = true
  unused-packages = true
