apiVersion: v1
kind: Namespace
metadata:
  name: edgetpu-demo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: edgetpu
  namespace: edgetpu-demo
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'system:openshift:scc:anyuid'
subjects:
  - kind: ServiceAccount
    name: edgetpu
    namespace: edgetpu-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:anyuid'
---
apiVersion: batch/v1
kind: Job
metadata:
  name: edgetpu-demo
  namespace: edgetpu-demo
spec:
  backoffLimit: 4
  template:
    spec:
      serviceAccountName: edgetpu
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
      - name: edgetpu-demo
        image: quay.io/revoman/edgetpu-demo:amd64
        imagePullPolicy: Always
        command:
          - python3
          - examples/classify_image.py
          - -i
          - test_data/parrot.jpg
          - -m
          - test_data/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite
          - -l
          - test_data/inat_bird_labels.txt
        resources:
          limits:
            kkohtaka.org/edgetpu: 1
      restartPolicy: Never
